export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";

export const LOGOUT_ERROR = "LOGOUT ERROR";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";

export const IS_LOADING = "IS_LOADING";
export const HAS_LOADED = "HAS_LOADED";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR";
